<?php
$z[0]=Array("field","",32,60);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",77,106);
$z[1][4]['name']="typename";
$z[2]=Array("global","if(@me==1){@me='ABOUT'; }if(@me==2){@me='DYNAMIC'; } if(@me==3){@me='INDUSTRY'; }if(@me==4){@me='HENGQIN'; } if(@me==5){@me='HR'; }if(@me==6){@me='CONTACT US'; }",139,355);
$z[2][4]['name']="itemindex";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",389,521);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>