<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",907,942);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li onClick=\"location.href='[field:typeurl/]';\">\r\n          <div class=\"navmborder\"></div>\r\n          <div id=\"navmtext\">\r\n            <h2> <a title=\"[field:typename/]\" href=\"[field:typeurl/]\">[field:typename/]</a></h2>\r\n          </div>\r\n        </li>\r\n        ",1377,1680);
$z[6]=Array("field","",1788,1810);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1846,1867);
$z[7][4]['name']="content";
$z[8]=Array("include","",1939,1976);
$z[8][4]['filename']="footer.htm";

?>