<?php
$z[0]=Array("field","",256,275);
$z[0][4]['name']="title";
$z[1]=Array("global","",276,302);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",343,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",405,456);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",936,971);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1197,1216);
$z[5][4]['name']="title";
$z[6]=Array("field","",1304,1360);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",1381,1403);
$z[7][4]['name']="typename";
$z[8]=Array("field","",1425,1445);
$z[8][4]['name']="source";
$z[9]=Array("field","",1503,1521);
$z[9][4]['name']="body";
$z[10]=Array("include","",1572,1609);
$z[10][4]['filename']="footer.htm";

?>