<?php
$z[0]=Array("global","",151,174);
$z[0][4]['name']="cfg_copy";
$z[1]=Array("global","",197,221);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n              ",399,554);
$z[2][4]['typeid']="29";
$z[2][4]['limit']="0,10";
$z[3]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\"  target=\"_blank\">[field:title/]</a></li>\r\n              ",721,877);
$z[3][4]['typeid']="30";
$z[3][4]['limit']="0,10";

?>