<?php
$z[0]=Array("channelartlist","\r\n    <li class=\"mainlevel\"> <a href=\"{dede:field name='typeurl'/}\"><span id=\"cnf\">{dede:field name='typename'/}</span><br/>\r\n      <span id=enf>{dede:global name=itemindex runphp='yes'}if(@me==1){@me='ABOUT'; }if(@me==2){@me='DYNAMIC'; } if(@me==3){@me='INDUSTRY'; }if(@me==4){@me='HENGQIN'; } if(@me==5){@me='HR'; }if(@me==6){@me='CONTACT US'; }{/dede:global}</span> </a>\r\n      <ul>\r\n        {dede:channel type='son' noself='yes' }\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        {/dede:channel}\r\n      </ul>\r\n    </li>\r\n    ",438,1073);
$z[0][4]['row']="20";
$z[0][4]['typeid']="1,7,11,18,23,28";

?>