<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1136,1171);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n    <dl id=\"y_ywsmenu\" onClick=\"location.href='[field:typeurl/]';\">\r\n      <dt>0[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global] </dt>\r\n      <dd>[field:typename/]</dd>\r\n    </dl>\r\n    ",1327,1564);
$z[6]=Array("field","",1610,1631);
$z[6][4]['name']="content";
$z[7]=Array("include","",1698,1735);
$z[7][4]['filename']="footer.htm";

?>